/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bubelrobert (https://sketchfab.com/bubelrobert)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/tesla-cybertruck-5a86defda4b24836a504fe5e597fdb17
title: Tesla - Cybertruck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cyber.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh position={[-0.1, -0.5, 0.1]} scale={0.115}
       >
      <group rotation={[-Math.PI / 2.05, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.53, 97.99, 103.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[94.78, 100, 100]}>
            <mesh geometry={nodes.INTERIOR_interior_0.geometry} material={materials.interior} />
            <mesh geometry={nodes.INTERIOR_screen_0.geometry} material={materials.screen} />
          </group>
          <group position={[-429.78, 252.99, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.LOGO_LOGO_0.geometry} material={materials.LOGO} />
          </group>
          <group position={[-2.21, 88.09, -35.18]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BODY_light_0.geometry} material={materials.light} />
            <mesh geometry={nodes.BODY_BOT_0.geometry} material={materials.material} />
            <mesh geometry={nodes.BODY_METAL_0.geometry} material={materials.METAL} />
            <mesh geometry={nodes.BODY_METAL001_0.geometry} material={materials['METAL.001']} />
            <mesh geometry={nodes.BODY_WINDOW_0.geometry} material={materials.WINDOW} />
            <mesh geometry={nodes.BODY_METAL002_0.geometry} material={materials['METAL.002']} />
            <mesh geometry={nodes.BODY_WINDOW001_0.geometry} material={materials['WINDOW.001']} />
            <mesh geometry={nodes.BODY_WINDOW_TOP_0.geometry} material={materials.WINDOW_TOP} />
            <mesh geometry={nodes.BODY_BUMBERS_0.geometry} material={materials.BUMBERS} />
            <mesh geometry={nodes.BODY_RIMS_0.geometry} material={materials.RIMS} />
            <mesh geometry={nodes.BODY_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.BODY_RED_lighter_0.geometry} material={materials.RED_lighter} />
            <mesh geometry={nodes.BODY_BumberLight_0.geometry} material={materials.BumberLight} />
            <mesh geometry={nodes.BODY_ramkatyl_0.geometry} material={materials.ramkatyl} />
            <mesh geometry={nodes.BODY_KIERUNKI_0.geometry} material={materials.KIERUNKI} />
          </group>
          <group position={[-2.17, 42.95, -283.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.PLATE_Plate_0.geometry} material={materials.Plate} />
          </group>
          <group position={[-0.53, 97.99, 103.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[94.78, 100, 100]}>
            <mesh geometry={nodes.INTERIOR001_interior_0.geometry} material={materials.interior} />
          </group>
          <group position={[-105.7, 3.7, 198.12]} rotation={[-Math.PI / 2, 0, 0]} scale={95.56}>
            <mesh geometry={nodes.RIGHT_FRONT_WHEEL_Tire_Rubber_0.geometry} material={materials.Tire_Rubber} />
            <mesh geometry={nodes.RIGHT_FRONT_WHEEL_RIMS_0.geometry} material={materials.RIMS} />
          </group>
          <group position={[-105.7, 3.7, -185.81]} rotation={[-Math.PI / 2, 0, 0]} scale={95.56}>
            <mesh geometry={nodes.RIGHT_BACK_WHEEL_Tire_Rubber_0.geometry} material={materials.Tire_Rubber} />
            <mesh geometry={nodes.RIGHT_BACK_WHEEL_RIMS_0.geometry} material={materials.RIMS} />
          </group>
          <group position={[101.28, 3.7, -185.81]} rotation={[-Math.PI / 2, 0, 0]} scale={95.56}>
            <mesh geometry={nodes.LEFT_BACK_WHEEL_Tire_Rubber_0.geometry} material={materials.Tire_Rubber} />
            <mesh geometry={nodes.LEFT_BACK_WHEEL_RIMS_0.geometry} material={materials.RIMS} />
          </group>
          <group position={[101.28, 3.7, 198.12]} rotation={[-Math.PI / 2, 0, 0]} scale={95.56}>
            <mesh geometry={nodes.LEFT_FRONT_WHEEL_Tire_Rubber_0.geometry} material={materials.Tire_Rubber} />
            <mesh geometry={nodes.LEFT_FRONT_WHEEL_RIMS_0.geometry} material={materials.RIMS} />
          </group>
        </group>
      </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/cyber.gltf')
