/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: petiixblender (https://sketchfab.com/petii10)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/cyberpunk-2077-quadra-cybertruck-b6c6aa4f8b614e91ad277533cc5a4f18
title: Cyberpunk 2077 - Quadra Cybertruck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cybertruck.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -0.93]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.UVs.008']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.033']} />
          </group>
          <group position={[-1.03, 1.2, 0.45]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.UVs.008']} />
          </group>
          <group position={[-0.17, 0.52, 0]} rotation={[0, 0, -0.07]} scale={[0.01, 0.17, 0.17]}>
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.UVs.001']} />
          </group>
          <group position={[0.09, -0.04, -0.03]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-0.67, 0.21, 0.5]} rotation={[0, 0, 0.06]} scale={0.04}>
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.UVs.008']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} />
          </group>
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.UVs.005']} />
          <mesh geometry={nodes.Object_19.geometry} material={materials['Material.007']} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Material.004']} />
          <group position={[0.64, 0.36, 0.15]} rotation={[0.21, 0, 0]} scale={[0.15, 0.08, 0.11]}>
            <mesh geometry={nodes.Object_22.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-1.41, 0, 0.42]} rotation={[-0.04, 0.68, 0.05]} scale={0.04}>
            <mesh geometry={nodes.Object_24.geometry} material={materials['Material.004']} />
          </group>
          <group position={[0.84, 0.31, 0.27]} rotation={[0, -0.11, -0.04]} scale={0.06}>
            <mesh geometry={nodes.Object_26.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-1.34, 0.15, 0.32]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
            <mesh geometry={nodes.Object_28.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-0.1, -0.2, 0.02]} scale={[0.65, 1.05, 0.44]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials['Material.007']} />
          </group>
          <mesh geometry={nodes.Object_33.geometry} material={materials['Material.UVs.008']} />
          <group position={[0.42, 0.18, 0]} rotation={[0, 0, 1.45]} scale={0.49}>
            <mesh geometry={nodes.Object_35.geometry} material={materials.material_0} />
          </group>
          <group position={[0.02, 0.06, -0.02]} scale={1.06}>
            <mesh geometry={nodes.Object_37.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Object_38.geometry} material={materials['Material.017']} />
          </group>
          <group position={[-0.73, 0.26, 0]} rotation={[0, 0, -Math.PI]} scale={[-0.12, 0.01, 0.45]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Object_41.geometry} material={materials['Material.016']} />
          </group>
          <group position={[-0.5, 0.27, 0]} rotation={[0, 0, 0.17]} scale={[0, 0.07, 0.11]}>
            <mesh geometry={nodes.Object_43.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Object_44.geometry} material={materials['Material.019']} />
          </group>
          <group position={[0.25, 0.21, 0]} rotation={[0, 0, -0.39]} scale={[0.05, 0.18, 0.23]}>
            <mesh geometry={nodes.Object_46.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Object_47.geometry} material={materials['Material.017']} />
          </group>
          <group position={[-0.43, 0.23, 0.27]} rotation={[Math.PI / 2, 0.33, -Math.PI / 2]} scale={0.05}>
            <mesh geometry={nodes.Object_49.geometry} material={materials['Material.017']} />
            <mesh geometry={nodes.Object_50.geometry} material={materials['Material.010']} />
            <mesh geometry={nodes.Object_51.geometry} material={materials['Material.018']} />
          </group>
          <group position={[0, 0.13, 0]} scale={[1, 0.39, 1]}>
            <mesh geometry={nodes.Object_53.geometry} material={materials['Material.UVs.010']} />
            <mesh geometry={nodes.Object_54.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_55.geometry} material={materials['Material.UVs.011']} />
            <mesh geometry={nodes.Object_56.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_57.geometry} material={materials['Material.UVs.001']} />
            <mesh geometry={nodes.Object_58.geometry} material={materials['Material.UVs.008']} />
            <mesh geometry={nodes.Object_59.geometry} material={materials['Material.UVs.012']} />
          </group>
          <group position={[-0.05, -0.06, 0.52]} rotation={[-1.5, Math.PI / 2, 0]} scale={[0.03, 0.09, 0.09]}>
            <mesh geometry={nodes.Object_61.geometry} material={materials['Material.UVs.005']} />
          </group>
          <group position={[-0.05, -0.23, 0.49]} rotation={[0, 0, -Math.PI]} scale={[-0.71, 0.03, 0.02]}>
            <mesh geometry={nodes.Object_63.geometry} material={materials['Material.UVs.009']} />
          </group>
          <group position={[-1.36, -0.15, 0.25]} scale={[0.08, 0.08, 0.25]}>
            <mesh geometry={nodes.Object_65.geometry} material={materials['Material.UVs.010']} />
            <mesh geometry={nodes.Object_66.geometry} material={materials['Material.004']} />
          </group>
          <group position={[1.33, -0.07, 0]} scale={[0.09, 0.03, 0.47]}>
            <mesh geometry={nodes.Object_68.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1.33, -0.21, 0]} scale={[0.13, 0.13, 0.52]}>
            <mesh geometry={nodes.Object_70.geometry} material={materials['Material.UVs.007']} />
          </group>
          <group position={[-1.03, -0.2, 0.45]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.2, 0.2, 0.16]}>
            <group position={[0, 0.03, -0.55]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.98}>
              <mesh geometry={nodes.Object_74.geometry} material={materials['Material.UVs.003']} />
            </group>
            <group position={[0, 0, -0.33]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.84}>
              <mesh geometry={nodes.Object_76.geometry} material={materials['Material.UVs.006']} />
            </group>
            <mesh geometry={nodes.Object_72.geometry} material={materials['Material.008']} />
          </group>
          <group position={[-0.78, -0.2, 0.47]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.01}>
            <mesh geometry={nodes.Object_78.geometry} material={materials['Material.008']} />
          </group>
          <group position={[-1.03, -0.2, 0.66]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.23}>
            <mesh geometry={nodes.Object_80.geometry} material={materials['Material.008']} />
          </group>
          <group position={[0.31, 0.13, 0]} scale={[1, 0.39, 1]}>
            <mesh geometry={nodes.Object_82.geometry} material={materials['Material.UVs.008']} />
          </group>
          <group position={[0, 0.13, 0]} scale={[1, 0.39, 1]}>
            <mesh geometry={nodes.Object_84.geometry} material={materials['Material.UVs.008']} />
          </group>
          <group position={[0, 0.13, 0]} scale={[1, 0.39, 1]}>
            <mesh geometry={nodes.Object_86.geometry} material={materials['Material.UVs.008']} />
            <mesh geometry={nodes.Object_87.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cybertruck.gltf')
