/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: arthur (https://sketchfab.com/Arthur_mf)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ethereum-ac40cebf61464c548776a0c20b47ccc7
title: Ethereum
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/eth.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
       <mesh position={[-0.1, -0.5, 0.1]} scale={1}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.22, 0, -0.38]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-0.22, 0, -0.38]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.005']} />
          </group>
          <group position={[3, 0, -0.99]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.007']} />
          </group>
          <group position={[3, 0, -0.99]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.003']} />
          </group>
          <group position={[3, 0, -0.99]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-0.22, 0, -0.38]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
          </group>
        </group>
      </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/eth.gltf')
