/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: donalleniii (https://sketchfab.com/donalleniii)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/tesla-bot-a65fe7cd17814149936912300fb8620b
title: Tesla Bot
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/perfil.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <mesh position={[0, -27, 0]} scale={15}>
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="7632b4704f9b4287af904a9b9eee8ffbfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Textures} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    </mesh>
  )
}

useGLTF.preload('/perfil.gltf')
