/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kreanym (https://sketchfab.com/kreanym)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cyberpunk-2077-quadra-v-tech-6c8bc8c16f2c4e739b2f182e9d060873
title: Cyberpunk 2077 - Quadra V-Tech
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/quadra.gltf')

  console.log(materials)
  return (
    <group ref={group} {...props} dispose={null}>
       <mesh position={[-0.1, -1.5, 0.1]} scale={1.2}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.29}>
        <mesh geometry={nodes.Boden_0.geometry} material={materials.Boden}  />
        <mesh geometry={nodes['V-Tech_0'].geometry} material={materials.Material} />
        <group position={[2.05, -7.98, 1.12]} rotation={[Math.PI / 2, 0.12, 0]} scale={[0.1, 0.15, 0.2]}>
          <mesh geometry={nodes['01_Aufkleber_Quadra_vorne_0'].geometry} material={materials.Material} />
        </group>
        <mesh geometry={nodes.Rippen_hinten_guide_0.geometry} material={materials.Material} />
        <group position={[-1.75, -8.09, 1.23]} rotation={[0, 0, -Math.PI]} scale={[0.56, 0.03, 0.24]}>
          <mesh geometry={nodes.Sketchfab_Nummernschild_vorne_0.geometry} material={materials.Material} />
        </group>
        <mesh geometry={nodes.Sketchfab_Spoilerstangen_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Heckzeugs_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Karosserie_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Kotfluegel_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Rad_vorne_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Rad_hinten_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Radlauf_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Spoiler_0.geometry} material={materials.Material} />
        <group position={[1.42, 0, 0]}>
          <mesh geometry={nodes.Sketchfab_Stange_0.geometry} material={materials.Material} />
        </group>
        <mesh geometry={nodes.Sketchfab_Luftfilter_0.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sketchfab_Auspuff_0.geometry} material={materials.Material} />
        <group position={[0.77, 0, 0]}>
          <mesh geometry={nodes.Sketchfab_Stange001_0.geometry} material={materials.Material} />
        </group>
        <group position={[-1.41, 0, 0]}>
          <mesh geometry={nodes.Sketchfab_Stange002_0.geometry} material={materials.Material} />
        </group>
        <group position={[-0.76, 0, 0]}>
          <mesh geometry={nodes.Sketchfab_Stange003_0.geometry} material={materials.Material} />
        </group>
        <group position={[0, 8.13, 1.81]} scale={[0.56, 0.03, 0.24]}>
          <mesh geometry={nodes.Sketchfab_Nummernschild_vorne001_0.geometry} material={materials.Material} />
        </group>
        <group position={[1.78, 8.37, 2.89]} rotation={[-1.15, 0.01, 3.14]} scale={[0.1, 0.15, 0.2]}>
          <mesh geometry={nodes['01_Aufkleber_Quadra_vorne001_0'].geometry} material={materials.Material} />
        </group>
      </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/quadra.gltf')
