/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: wintrez (https://sketchfab.com/wintrez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tesla-m3-model-3a602469d7874d1397efa67182198705
title: Tesla M3 model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/redtesla.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh position={[-0.1, 0, 0.1]} scale={0.4}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
        
          <mesh geometry={nodes.Object_4.geometry} material={materials.carpaint} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.BlackWash} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.glass} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.glassDark} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.OrangeLights} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.Mirror} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Silver} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.innerLights} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.innerLightMetals} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.RedLight} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.TireRubber} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Tire_Rims} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Breaks} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.carBrand} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.GlossyInterior} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.LightGrayInterior} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.interiorGray} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.BlackSuade} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.White} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.LicensePlateText} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.LicensePlateRed} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.LicensePlateYellow} />
        </group>
      </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/redtesla.gltf')
