/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ahad4940 (https://sketchfab.com/Ahad4940)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tesla-bot-customized-76691ba09fea46d5b225c8345a8f31ff
title: Tesla Bot customized
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/robot.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh position={[-0.2, -2.3, -0.2]} scale={3.4}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.85}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Textures} skeleton={nodes.Object_7.skeleton} />
        </group>
      </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/robot.gltf')
