/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bubelrobert (https://sketchfab.com/bubelrobert)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/free-tesla-tequila-a469399f7e4e428ca70bc923fab766d5
title: [FREE] Tesla Tequila
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tequila.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 4.2]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh position={[-0.2, -1.9, -0.2]} scale={0.129}>
          <group position={[-0.27, 6.16, -4.6]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane_bottleinside_0.geometry} material={materials['bottle.inside']} />
          </group>
          <group position={[-0.91, 4.1, -3.89]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.17, 4.49, 4.49]}>
            <mesh geometry={nodes.Plane001_metal_0.geometry} material={materials.metal} />
          </group>
          <group position={[-0.23, 0.63, 3.81]} rotation={[-Math.PI / 2, 0, 0]} scale={51.58}>
            <mesh geometry={nodes.Plane002_decals_0.geometry} material={materials.decals} />
          </group>
          <group position={[3.24, 19.56, 0.47]} rotation={[Math.PI / 2, 0, 0]} scale={111.84}>
            <mesh geometry={nodes.Plane003_decals_0.geometry} material={materials.decals} />
          </group>
          <group position={[-2.85, 6.16, -4.57]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.17, 4.49, 4.49]}>
            <mesh geometry={nodes.Plane004_decals_0.geometry} material={materials.decals} />
          </group>
          <group position={[-0.27, 6.16, -4.6]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane005_bottle_0.geometry} material={materials.bottle} />
          </group>
          <group position={[-0.27, 6.16, -4.6]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane006_bottleinside_0.geometry} material={materials['bottle.inside']} />
          </group>
          <group position={[-0.27, 6.16, -4.6]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.17, 4.49, 4.49]}>
            <mesh geometry={nodes.Plane007_bottle_0.geometry} material={materials.bottle} />
          </group>
          <group position={[-0.27, 32.01, 2.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.72, 0.72, 1.66]}>
            <mesh geometry={nodes.Cylinder_plug_0.geometry} material={materials.plug} />
          </group>
          </mesh>
        </group>
        
      </group>
    </group>
  )
}

useGLTF.preload('/tequila.gltf')
