/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: charmmingeyes (https://sketchfab.com/charmmingeyes)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tesla-b89f5920ec0244e19992c6a4027dd969
title: tesla
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tesla.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, -0.11, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.2}>
        <mesh position={[-0.1, -5, 0.1]} scale={0.1}
       >
          <group position={[-50.46, 48.89, 2.15]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-1-240_Obj3d66-806492-1-240_mtl_0'].geometry} material={materials['Obj3d66-806492-1-240_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-2-131_Obj3d66-806492-2-131_mtl_0'].geometry} material={materials['Obj3d66-806492-2-131_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-3-675_Obj3d66-806492-3-675_mtl_0'].geometry} material={materials['Obj3d66-806492-3-675_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-4-3_Obj3d66-806492-4-3_mtl_0'].geometry} material={materials['Obj3d66-806492-4-3_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-5-589_Obj3d66-806492-5-589_mtl_0'].geometry} material={materials['Obj3d66-806492-5-589_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-6-551_Obj3d66-806492-6-551_mtl_0'].geometry} material={materials['Obj3d66-806492-6-551_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-7-75_Obj3d66-806492-7-75_mtl_0'].geometry} material={materials['Obj3d66-806492-7-75_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-8-660_Obj3d66-806492-8-660_mtl_0'].geometry} material={materials['Obj3d66-806492-8-660_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-9-666_Obj3d66-806492-9-666_mtl_0'].geometry} material={materials['Obj3d66-806492-9-666_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-10-876_Obj3d66-806492-10-876_mtl_0'].geometry} material={materials['Obj3d66-806492-10-876_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-11-377_Obj3d66-806492-11-377_mtl_0'].geometry} material={materials['Obj3d66-806492-11-377_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-12-456_Obj3d66-806492-12-456_mtl_0'].geometry} material={materials['Obj3d66-806492-12-456_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-13-856_Obj3d66-806492-13-856_mtl_0'].geometry} material={materials['Obj3d66-806492-13-856_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-14-563_Obj3d66-806492-14-563_mtl_0'].geometry} material={materials['Obj3d66-806492-14-563_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-15-836_Obj3d66-806492-15-836_mtl_0'].geometry} material={materials['Obj3d66-806492-15-836_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-16-476_Obj3d66-806492-16-476_mtl_0'].geometry} material={materials['Obj3d66-806492-16-476_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-17-895_Obj3d66-806492-17-895_mtl_0'].geometry} material={materials['Obj3d66-806492-17-895_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-18-503_Obj3d66-806492-18-503_mtl_0'].geometry} material={materials['Obj3d66-806492-18-503_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-19-296_Obj3d66-806492-19-296_mtl_0'].geometry} material={materials['Obj3d66-806492-19-296_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-20-679_Obj3d66-806492-20-679_mtl_0'].geometry} material={materials['Obj3d66-806492-20-679_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-21-439_Obj3d66-806492-21-439_mtl_0'].geometry} material={materials['Obj3d66-806492-21-439_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-22-733_Obj3d66-806492-22-733_mtl_0'].geometry} material={materials['Obj3d66-806492-22-733_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-23-981_Obj3d66-806492-23-981_mtl_0'].geometry} material={materials['Obj3d66-806492-23-981_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-24-582_Obj3d66-806492-24-582_mtl_0'].geometry} material={materials['Obj3d66-806492-24-582_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-25-870_Obj3d66-806492-25-870_mtl_0'].geometry} material={materials['Obj3d66-806492-25-870_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-26-53_Obj3d66-806492-26-53_mtl_0'].geometry} material={materials['Obj3d66-806492-26-53_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-27-306_Obj3d66-806492-27-306_mtl_0'].geometry} material={materials['Obj3d66-806492-27-306_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-28-205_Obj3d66-806492-28-205_mtl_0'].geometry} material={materials['Obj3d66-806492-28-205_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-29-796_Obj3d66-806492-29-796_mtl_0'].geometry} material={materials['Obj3d66-806492-29-796_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-30-629_Obj3d66-806492-30-629_mtl_0'].geometry} material={materials['Obj3d66-806492-30-629_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-31-938_Obj3d66-806492-31-938_mtl_0'].geometry} material={materials['Obj3d66-806492-31-938_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-32-111_Obj3d66-806492-32-111_mtl_0'].geometry} material={materials['Obj3d66-806492-32-111_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-33-226_Obj3d66-806492-33-226_mtl_0'].geometry} material={materials['Obj3d66-806492-33-226_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-34-181_Obj3d66-806492-34-181_mtl_0'].geometry} material={materials['Obj3d66-806492-34-181_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-35-823_Obj3d66-806492-35-823_mtl_0'].geometry} material={materials['Obj3d66-806492-35-823_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-36-884_Obj3d66-806492-36-884_mtl_0'].geometry} material={materials['Obj3d66-806492-36-884_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-37-885_Obj3d66-806492-37-885_mtl_0'].geometry} material={materials['Obj3d66-806492-37-885_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-38-848_Obj3d66-806492-38-848_mtl_0'].geometry} material={materials['Obj3d66-806492-38-848_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-39-404_Obj3d66-806492-39-404_mtl_0'].geometry} material={materials['Obj3d66-806492-39-404_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-40-906_Obj3d66-806492-40-906_mtl_0'].geometry} material={materials['Obj3d66-806492-40-906_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-41-630_Obj3d66-806492-41-630_mtl_0'].geometry} material={materials['Obj3d66-806492-41-630_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-42-327_Obj3d66-806492-42-327_mtl_0'].geometry} material={materials['Obj3d66-806492-42-327_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-43-734_Obj3d66-806492-43-734_mtl_0'].geometry} material={materials['Obj3d66-806492-43-734_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-44-758_Obj3d66-806492-44-758_mtl_0'].geometry} material={materials['Obj3d66-806492-44-758_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-45-447_Obj3d66-806492-45-447_mtl_0'].geometry} material={materials['Obj3d66-806492-45-447_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-46-373_Obj3d66-806492-46-373_mtl_0'].geometry} material={materials['Obj3d66-806492-46-373_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-47-720_Obj3d66-806492-47-720_mtl_0'].geometry} material={materials['Obj3d66-806492-47-720_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-48-93_Obj3d66-806492-48-93_mtl_0'].geometry} material={materials['Obj3d66-806492-48-93_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-49-994_Obj3d66-806492-49-994_mtl_0'].geometry} material={materials['Obj3d66-806492-49-994_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-50-260_Obj3d66-806492-50-260_mtl_0'].geometry} material={materials['Obj3d66-806492-50-260_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-51-206_Obj3d66-806492-51-206_mtl_0'].geometry} material={materials['Obj3d66-806492-51-206_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-52-333_Obj3d66-806492-52-333_mtl_0'].geometry} material={materials['Obj3d66-806492-52-333_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-53-154_Obj3d66-806492-53-154_mtl_0'].geometry} material={materials['Obj3d66-806492-53-154_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-54-299_Obj3d66-806492-54-299_mtl_0'].geometry} material={materials['Obj3d66-806492-54-299_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-55-115_Obj3d66-806492-55-115_mtl_0'].geometry} material={materials['Obj3d66-806492-55-115_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-56-26_Obj3d66-806492-56-26_mtl_0'].geometry} material={materials['Obj3d66-806492-56-26_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-57-570_Obj3d66-806492-57-570_mtl_0'].geometry} material={materials['Obj3d66-806492-57-570_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-58-993_Obj3d66-806492-58-993_mtl_0'].geometry} material={materials['Obj3d66-806492-58-993_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-59-373_Obj3d66-806492-59-373_mtl_0'].geometry} material={materials['Obj3d66-806492-59-373_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-60-208_Obj3d66-806492-60-208_mtl_0'].geometry} material={materials['Obj3d66-806492-60-208_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-61-638_Obj3d66-806492-61-638_mtl_0'].geometry} material={materials['Obj3d66-806492-61-638_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-62-943_Obj3d66-806492-62-943_mtl_0'].geometry} material={materials['Obj3d66-806492-62-943_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-63-828_Obj3d66-806492-63-828_mtl_0'].geometry} material={materials['Obj3d66-806492-63-828_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-64-616_Obj3d66-806492-64-616_mtl_0'].geometry} material={materials['Obj3d66-806492-64-616_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-65-910_Obj3d66-806492-65-910_mtl_0'].geometry} material={materials['Obj3d66-806492-65-910_mtl']} />
          </group>
          <group position={[-50.44, 48.92, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-66-78_Obj3d66-806492-66-78_mtl_0'].geometry} material={materials['Obj3d66-806492-66-78_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-67-891_Obj3d66-806492-67-891_mtl_0'].geometry} material={materials['Obj3d66-806492-67-891_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-68-92_Obj3d66-806492-68-92_mtl_0'].geometry} material={materials['Obj3d66-806492-68-92_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-69-394_Obj3d66-806492-69-394_mtl_0'].geometry} material={materials['Obj3d66-806492-69-394_mtl']} />
          </group>
          <group position={[-50.44, 48.89, 2.18]} rotation={[0, 0, Math.PI / 2]}>
            <mesh geometry={nodes['Obj3d66-806492-70-322_Obj3d66-806492-70-322_mtl_0'].geometry} material={materials['Obj3d66-806492-70-322_mtl']} />
          </group>
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tesla.gltf')
